version: '3.1'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  service-registry:
    image: service-registry:latest
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - default

  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
    environment:
      EUREKA_SERVER_URL: http://service-registry:8761/eureka/
    networks:
      - default

  auth-service:
    image: auth-service:latest
    container_name: auth-service
    ports:
      - "8083:8083"
    depends_on:
      - service-registry
    environment:
      EUREKA_SERVER_URL: http://service-registry:8761/eureka/
    networks:
      - default

    # Add other microservices here

networks:
  default:
    driver: bridge
