#"# Server properties
#server:
#  port: 8085
#
## Application properties
#spring:
#  application:
#    name: chat-service
#
#  # Datasource properties
#  datasource:
#    url: jdbc:mysql://localhost:3306/chat_service
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: "@springboot123"


server:
  port: 8085

  # Application properties
spring:
  application:
    name: chat-service

  # Datasource properties
  datasource:
    url: jdbc:mysql://localhost:3306/chat_service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "@springboot123"

  # Jpa properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka